from __future__ import annotations

import json
import math
import os
import traceback
from pathlib import Path
from typing import Any, Callable

OUTPUT_FILE = Path(os.environ.get("BIKE_REBALANCE_REPORT", "/root/report.json"))
DATA_FILE = Path(os.environ.get("BIKE_REBALANCE_DATA", "/root/data.json"))
LOG_DIR = Path(os.environ.get("VERIFIER_LOG_DIR", "/logs/verifier"))

START = "depot_start"
END = "depot_end"
TOL = 1e-5
TOL_DISTANCE = 1e-3
TOL_OBJECTIVE = 1e-3
TOL_INTEGER = 1e-5
TOL_LOAD = 1e-5

# Fixed controlled-local-snapshot benchmark for this approved data.json.
# The bound is generated by the zero-dependency constructive oracle and keeps
# the original verifier's quality gate shape: feasible reports must be no worse
# than a deterministic benchmark objective for the same pinned input package.
SNAPSHOT_BENCHMARK_OBJECTIVE = 9.975584


class VerifierFailure(AssertionError):
    pass


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(float(value))


def _as_float(value: Any, label: str) -> float:
    if not _is_number(value):
        raise VerifierFailure(f"{label} must be a finite number, got {value!r}")
    return float(value)


def _as_station_id(value: Any, label: str) -> int:
    if isinstance(value, bool):
        raise VerifierFailure(f"{label} must be an integer station id, got {value!r}")
    if isinstance(value, int):
        return int(value)
    if isinstance(value, float) and math.isfinite(value) and abs(value - round(value)) <= TOL_INTEGER:
        return int(round(value))
    raise VerifierFailure(f"{label} must be an integer station id, got {value!r}")


def _assert_close(actual: float, expected: float, label: str, tol: float = TOL) -> None:
    diff = abs(float(actual) - float(expected))
    limit = max(tol, tol * max(1.0, abs(float(expected))))
    if diff > limit:
        raise VerifierFailure(f"{label}: actual={actual:.8f}, expected={expected:.8f}, diff={diff:.8g}")


def _assert_integer_like(value: float, label: str) -> None:
    if abs(value - round(value)) > TOL_INTEGER:
        raise VerifierFailure(f"{label} must be integer-valued, got {value!r}")


def great_circle_miles(a: dict[str, float], b: dict[str, float]) -> float:
    lat1 = float(a["latitude"])
    lon1 = float(a["longitude"])
    lat2 = float(b["latitude"])
    lon2 = float(b["longitude"])
    degrees_to_radians = math.pi / 180.0
    phi1 = (90.0 - lat1) * degrees_to_radians
    phi2 = (90.0 - lat2) * degrees_to_radians
    theta1 = lon1 * degrees_to_radians
    theta2 = lon2 * degrees_to_radians
    cos_arc = math.sin(phi1) * math.sin(phi2) * math.cos(theta1 - theta2) + math.cos(phi1) * math.cos(phi2)
    cos_arc = max(-1.0, min(1.0, cos_arc))
    return math.acos(cos_arc) * 3960.0


def _node_location(node: int | str, data: dict[str, Any], station_by_id: dict[int, dict[str, Any]]) -> dict[str, float]:
    if node in (START, END):
        return data["depot"]
    return station_by_id[int(node)]


def _route_distance(route: list[int | str], data: dict[str, Any], station_by_id: dict[int, dict[str, Any]]) -> float:
    return sum(
        great_circle_miles(_node_location(i, data, station_by_id), _node_location(j, data, station_by_id))
        for i, j in zip(route, route[1:])
    )


def load_json(path: Path, label: str) -> dict[str, Any]:
    if not path.exists():
        raise VerifierFailure(f"{label} file does not exist: {path}")
    with path.open(encoding="utf-8") as f:
        value = json.load(f)
    if not isinstance(value, dict):
        raise VerifierFailure(f"{label} must be a JSON object")
    return value


def parse_case(data: dict[str, Any]) -> dict[str, Any]:
    required_top = ["vehicle_count", "vehicle_capacity", "penalty_weight", "distance_metric", "depot", "stations"]
    for field in required_top:
        if field not in data:
            raise VerifierFailure(f"data.json missing required field {field!r}")
    if data["distance_metric"] != "great_circle_miles":
        raise VerifierFailure(f"Unsupported distance_metric={data.get('distance_metric')!r}")
    if not isinstance(data["stations"], list) or not data["stations"]:
        raise VerifierFailure("data.json stations must be a nonempty list")

    station_by_id: dict[int, dict[str, Any]] = {}
    for pos, station in enumerate(data["stations"]):
        for field in ["id", "latitude", "longitude", "net_rebalancing_target", "initial_bikes", "station_capacity"]:
            if field not in station:
                raise VerifierFailure(f"Station row {pos} missing required field {field!r}")
        sid = _as_station_id(station["id"], f"data station row {pos} id")
        if sid in station_by_id:
            raise VerifierFailure(f"Duplicate station id {sid} in data.json")
        station_by_id[sid] = station

    return {
        "station_by_id": station_by_id,
        "station_ids": set(station_by_id),
        "vehicle_count": int(data["vehicle_count"]),
        "vehicle_capacity": float(data["vehicle_capacity"]),
        "penalty_weight": float(data["penalty_weight"]),
    }


def reconstruct_solution(report: dict[str, Any], data: dict[str, Any], parsed_case: dict[str, Any]) -> dict[str, Any]:
    station_by_id = parsed_case["station_by_id"]
    station_ids = parsed_case["station_ids"]
    vehicle_capacity = parsed_case["vehicle_capacity"]
    station_sums = {sid: {"pickup": 0.0, "dropoff": 0.0} for sid in station_ids}
    travel_distance = 0.0
    vehicles: list[dict[str, Any]] = []

    for vehicle_pos, vehicle in enumerate(report["vehicles"]):
        route_raw = vehicle["route"]
        if not isinstance(route_raw, list):
            raise VerifierFailure(f"Vehicle {vehicle_pos + 1} route must be a list")
        if len(route_raw) < 3:
            raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} route must include a station")
        if route_raw[0] != START or route_raw[-1] != END:
            raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} route must start/end at depots")

        station_route = [
            _as_station_id(node, f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} route node {idx}")
            for idx, node in enumerate(route_raw[1:-1], start=1)
        ]
        if len(station_route) != len(set(station_route)):
            raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} repeats a station")
        for sid in station_route:
            if sid not in station_by_id:
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} route uses unknown station {sid}")

        route: list[int | str] = [START, *station_route, END]
        travel_distance += _route_distance(route, data, station_by_id)

        stops_raw = vehicle["stops"]
        if not isinstance(stops_raw, list) or len(stops_raw) != len(station_route):
            raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stops must match route stations")

        start_load = _as_float(vehicle["start_load"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} start_load")
        end_load = _as_float(vehicle["end_load"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} end_load")
        if not (0.0 - TOL_LOAD <= start_load <= vehicle_capacity + TOL_LOAD):
            raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} start_load outside capacity")
        _assert_integer_like(start_load, f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} start_load")
        current_load = start_load
        stop_records: list[dict[str, Any]] = []

        for stop_pos, (expected_sid, stop) in enumerate(zip(station_route, stops_raw), start=1):
            if not isinstance(stop, dict):
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stop {stop_pos} must be an object")
            sid = _as_station_id(stop["station_id"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stop station_id")
            if sid != expected_sid:
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stop order does not match route")
            pickup = _as_float(stop["bikes_picked_up"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} pickup")
            dropoff = _as_float(stop["bikes_dropped_off"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} dropoff")
            load_after = _as_float(stop["load_after_stop"], f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} load_after_stop")
            if pickup < -TOL or dropoff < -TOL or (pickup > TOL and dropoff > TOL):
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stop {stop_pos} has invalid operation")
            if dropoff > current_load + TOL_LOAD:
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} stop {stop_pos} drops more than carried")
            expected_load = current_load + pickup - dropoff
            _assert_close(load_after, expected_load, f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} load transition", TOL_LOAD)
            if not (0.0 - TOL_LOAD <= load_after <= vehicle_capacity + TOL_LOAD):
                raise VerifierFailure(f"Vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} load outside capacity")
            for value, label in [(pickup, "pickup"), (dropoff, "dropoff"), (load_after, "load_after_stop")]:
                _assert_integer_like(value, f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} {label}")
            station_sums[sid]["pickup"] += pickup
            station_sums[sid]["dropoff"] += dropoff
            stop_records.append({"station_id": sid, "pickup": pickup, "dropoff": dropoff, "load_after": load_after})
            current_load = load_after

        _assert_close(end_load, current_load, f"vehicle {vehicle.get('vehicle_id', vehicle_pos + 1)} end_load", TOL_LOAD)
        vehicles.append({"vehicle_id": vehicle["vehicle_id"], "route": route, "station_route": station_route, "stops": stop_records})

    station_reports = {}
    total_unmet = 0.0
    for station_report in report["stations"]:
        sid = _as_station_id(station_report["station_id"], "station report station_id")
        if sid in station_reports:
            raise VerifierFailure(f"Duplicate station report for station {sid}")
        if sid not in station_by_id:
            raise VerifierFailure(f"Station report contains unknown station {sid}")
        station_reports[sid] = station_report
        pickup = station_sums[sid]["pickup"]
        dropoff = station_sums[sid]["dropoff"]
        net_change = pickup - dropoff
        target = float(station_by_id[sid]["net_rebalancing_target"])
        total_unmet += abs(target - net_change)

        _assert_close(float(station_report["net_rebalancing_target"]), target, f"station {sid} target")
        _assert_close(float(station_report["total_bikes_picked_up"]), pickup, f"station {sid} pickup")
        _assert_close(float(station_report["total_bikes_dropped_off"]), dropoff, f"station {sid} dropoff")
        _assert_close(float(station_report["net_bike_change"]), net_change, f"station {sid} net_change")
        _assert_close(float(station_report["unmet_rebalancing_amount"]), abs(target - net_change), f"station {sid} unmet")

        initial_bikes = float(station_by_id[sid]["initial_bikes"])
        station_capacity = float(station_by_id[sid]["station_capacity"])
        final_bikes = initial_bikes - pickup + dropoff
        if not (0.0 - TOL_LOAD <= final_bikes <= station_capacity + TOL_LOAD):
            raise VerifierFailure(f"Station {sid} final inventory {final_bikes} outside [0,{station_capacity}]")

    if set(station_reports) != station_ids:
        raise VerifierFailure("stations must report exactly the station ids from data.json")
    penalty = float(data["penalty_weight"]) * total_unmet
    objective = travel_distance + penalty
    return {"travel_distance": travel_distance, "total_unmet": total_unmet, "unmet_penalty": penalty, "objective": objective}


def assert_schema(report: dict[str, Any], parsed_case: dict[str, Any]) -> None:
    for field in ["summary", "vehicles", "stations"]:
        if field not in report:
            raise VerifierFailure(f"Missing top-level field: {field}")
    for field in ["objective", "travel_distance_miles", "unmet_rebalancing_penalty", "total_unmet_rebalancing_amount"]:
        if field not in report["summary"] or not _is_number(report["summary"][field]):
            raise VerifierFailure(f"summary.{field} must be present and numeric")
    vehicles = report["vehicles"]
    if not isinstance(vehicles, list) or len(vehicles) != parsed_case["vehicle_count"]:
        raise VerifierFailure(f"Expected {parsed_case['vehicle_count']} vehicles")
    vehicle_ids = [_as_station_id(v.get("vehicle_id"), "vehicle_id") for v in vehicles]
    if sorted(vehicle_ids) != list(range(1, parsed_case["vehicle_count"] + 1)):
        raise VerifierFailure(f"Vehicle ids must be exactly 1..{parsed_case['vehicle_count']}, got {vehicle_ids}")


def assert_objective(report: dict[str, Any], reconstructed: dict[str, Any]) -> None:
    _assert_close(float(report["summary"]["travel_distance_miles"]), reconstructed["travel_distance"], "summary.travel_distance_miles", TOL_DISTANCE)
    _assert_close(float(report["summary"]["total_unmet_rebalancing_amount"]), reconstructed["total_unmet"], "summary.total_unmet")
    _assert_close(float(report["summary"]["unmet_rebalancing_penalty"]), reconstructed["unmet_penalty"], "summary.unmet_penalty")
    _assert_close(float(report["summary"]["objective"]), reconstructed["objective"], "summary.objective", TOL_OBJECTIVE)
    allowed = SNAPSHOT_BENCHMARK_OBJECTIVE + max(TOL_OBJECTIVE, 1e-6 * SNAPSHOT_BENCHMARK_OBJECTIVE)
    if reconstructed["objective"] > allowed:
        raise VerifierFailure(
            f"Objective too high: reconstructed={reconstructed['objective']:.6f}, "
            f"snapshot benchmark={SNAPSHOT_BENCHMARK_OBJECTIVE:.6f}, allowed<={allowed:.6f}"
        )


def write_results(results: list[dict[str, Any]]) -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    passed = sum(1 for r in results if r["status"] == "passed")
    total = len(results)
    ctrf = {
        "results": {
            "tool": {"name": "stdlib-bike-rebalance-verifier"},
            "summary": {"tests": total, "passed": passed, "failed": total - passed},
            "tests": results,
        }
    }
    (LOG_DIR / "ctrf.json").write_text(json.dumps(ctrf, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (LOG_DIR / "reward.txt").write_text("1\n" if passed == total else "0\n", encoding="utf-8")


def run_test(name: str, fn: Callable[[], None], results: list[dict[str, Any]]) -> None:
    try:
        fn()
    except Exception as exc:
        results.append({"name": name, "status": "failed", "message": str(exc), "trace": traceback.format_exc()})
    else:
        results.append({"name": name, "status": "passed"})


def main() -> None:
    report = load_json(OUTPUT_FILE, "report")
    data = load_json(DATA_FILE, "data")
    parsed_case = parse_case(data)
    reconstructed: dict[str, Any] = {}
    results: list[dict[str, Any]] = []
    run_test("schema", lambda: assert_schema(report, parsed_case), results)
    run_test("reconstruct_solution", lambda: reconstructed.update(reconstruct_solution(report, data, parsed_case)), results)
    run_test("objective_and_snapshot_quality", lambda: assert_objective(report, reconstructed), results)
    write_results(results)


if __name__ == "__main__":
    main()
